CREATE TABLE `clients` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`firstname` VARCHAR(100) NOT NULL,
`lastname` VARCHAR(100) NOT NULL,
`city` VARCHAR(100) NOT NULL,
`street` VARCHAR(200) NOT NULL,
`postcode` INT NOT NULL
);
